---
sudo: required
language: bash
deploy:
  provider: script
  skip_cleanup: true
  script: .travis/releaser.sh
  on:
    branch: master
branches:
  only:
    - master
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
