---
- name: Create texfile collector dir
  file:
    path: "{{ ebpf_exporter_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0750

- name: Create config file
  template:
    src: config.yaml.j2
    dest: "{{ ebpf_exporter_config_dir }}/config.yaml"
    owner: root
    group: root
    mode: 0640
  notify: restart ebpf_exporter

- name: Allow ebpf_exporter port in SELinux on RedHat OS family
  seport:
    ports: "{{ ebpf_exporter_web_listen_address.split(':')[1] }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"
